# Generated by Django 4.2.2 on 2023-06-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='sex',
            field=models.CharField(choices=[('M', 'male'), ('F', 'Female'), ('O', 'other')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='mostwanted',
            name='sex',
            field=models.CharField(choices=[('M', 'male'), ('F', 'Female'), ('O', 'other')], default='Male', max_length=10),
        ),
    ]
