# Generated by Django 4.2.2 on 2023-06-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw_api', '0002_missingperson_sex_mostwanted_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='picture',
            field=models.ImageField(default='', upload_to='missing_persons/'),
        ),
        migrations.AlterField(
            model_name='mostwanted',
            name='picture',
            field=models.ImageField(default='', upload_to='wanted_persons/'),
        ),
    ]
