name: run manage.py runserver
on:
  schedule:
    - cron: '0 20 * * *' # runs once every day at 20:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2 # checks out repo content

      - name: setup python
        uses: actions/setup-python@v4 # setup python
        with:
          python-version: '3.10' # install python version 3.10

      - name: install python packages  
        run: |
          python -m pip install --upgrade pip
          python install -r requirements.txt

      - name: execute py script # runs manage.py
        run:
          python manage.py runserver

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
