name: Daily Runserver

# Controls when the action will run.  
on: 
   # Triggers the workflow on pull request events but only for the master branch 
  pull_request_target: 
     types: [assigned, opened, reopened] 
  
   # Allows you to run this workflow manually from the Actions tab 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2 # checks out repo contents

      - name: Setup Python
        uses: actions/setup-python@v2 # setup python
        with:
          python-version: '3.10' # install python version

      - name: Install Python packages  
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Execute py script # runs manage.py
        run: |
          python manage.py runserver

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
